import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const chileDate = (value = new Date()) => value.toLocaleDateString('sv-SE', { timeZone: 'America/Santiago' })
const addDays = (value, days) => {
  const [year, month, day] = value.split('-').map(Number)
  const shifted = new Date(Date.UTC(year, month - 1, day + days))
  return shifted.toLocaleDateString('sv-SE', { timeZone: 'UTC' })
}
const today = chileDate()

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, {
    ...options,
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}),
      ...(localStorage.token ? { Authorization: `Bearer ${localStorage.token}` } : {}) },
  })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'No se pudo completar la solicitud')
  return response.status === 204 ? null : response.json()
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ usuario: 'admin@killbichos.cl', clave: 'demo1234' })
  const [error, setError] = useState('')
  async function submit(event) {
    event.preventDefault(); setError('')
    try { const data = await request('/auth/login', { method: 'POST', body: JSON.stringify(form) }); localStorage.token = data.access_token; onLogin() }
    catch (err) { setError(err.message) }
  }
  return <main className="login-page"><div className="login-card"><div className="brand-mark">KB</div><p className="eyebrow">CONTROL DE PLAGAS</p><h1>Bienvenido a Kill Bichos</h1><p className="muted">Gestiona clientes, visitas y la agenda de tu equipo.</p><form onSubmit={submit}><label>Correo<input type="email" value={form.usuario} onChange={e => setForm({ ...form, usuario: e.target.value })} /></label><label>Contraseña<input type="password" value={form.clave} onChange={e => setForm({ ...form, clave: e.target.value })} /></label>{error && <div className="error">{error}</div>}<button className="primary full">Ingresar al panel</button></form></div></main>
}

function App() {
  const [logged, setLogged] = useState(Boolean(localStorage.token))
  const [view, setView] = useState('agenda')
  if (!logged) return <Login onLogin={() => setLogged(true)} />
  return <div className="app-shell"><aside><div className="logo"><span>KB</span><div><strong>Kill Bichos</strong><small>Panel operativo</small></div></div><nav><button className={view === 'agenda' ? 'active' : ''} onClick={() => setView('agenda')}>▦ <span>Agenda</span></button><button className={view === 'clientes' ? 'active' : ''} onClick={() => setView('clientes')}>♧ <span>Clientes</span></button></nav><div className="sidebar-bottom"><div className="user-chip"><div className="avatar">AK</div><div><strong>Admin Kill Bichos</strong><small>Administrador</small></div></div><button className="logout" onClick={() => { delete localStorage.token; setLogged(false) }}>Cerrar sesión</button></div></aside><main className="content">{view === 'agenda' ? <Agenda /> : <Clientes />}</main></div>
}

function Stat({ label, value, tone }) { return <div className="stat"><span className={`stat-icon ${tone}`}>●</span><div><small>{label}</small><strong>{value}</strong></div></div> }

function Agenda() {
  const [date, setDate] = useState(today), [operator, setOperator] = useState(''), [visits, setVisits] = useState([]), [operators, setOperators] = useState([]), [stats, setStats] = useState({}), [clients, setClients] = useState([]), [modal, setModal] = useState(false), [error, setError] = useState('')
  const load = () => Promise.all([request(`/panel/visitas?fecha=${date}${operator ? `&operador_id=${operator}` : ''}`), request('/panel/operadores'), request('/panel/stats'), request('/clientes')]).then(([v, o, s, c]) => { setVisits(v); setOperators(o); setStats(s); setClients(c) }).catch(e => setError(e.message))
  useEffect(() => { load() }, [date, operator])
  const grouped = useMemo(() => visits.reduce((acc, visit) => { const key = visit.fecha_hora.slice(11, 16); (acc[key] ||= []).push(visit); return acc }, {}), [visits])
  async function update(id, estado) { await request(`/panel/visitas/${id}`, { method: 'PATCH', body: JSON.stringify({ estado }) }); load() }
  return <><header className="topbar"><div><p className="eyebrow">OPERACIÓN DIARIA</p><h1>Agenda</h1><p className="muted">Coordina las visitas y mantén a tu equipo en movimiento.</p></div><button className="primary" onClick={() => setModal(true)}>＋ Nueva visita</button></header>{error && <div className="error banner">{error}</div>}<section className="stats"><Stat label="Clientes registrados" value={stats.clientes ?? '—'} tone="green" /><Stat label="Visitas para hoy" value={stats.visitas_hoy ?? '—'} tone="blue" /><Stat label="Visitas pendientes" value={stats.pendientes ?? '—'} tone="orange" /></section><section className="toolbar"><div className="date-picker"><button onClick={() => setDate(addDays(date, -1))}>‹</button><input type="date" value={date} onChange={e => setDate(e.target.value)} /><button onClick={() => setDate(addDays(date, 1))}>›</button></div><select value={operator} onChange={e => setOperator(e.target.value)}><option value="">Todos los operadores</option>{operators.map(o => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select><span className="today-label">{date === today ? 'Hoy' : new Date(`${date}T12:00:00`).toLocaleDateString('es-CL', { weekday: 'long', day: 'numeric', month: 'long' })}</span></section><section className="schedule"><div className="schedule-head"><span>Hora</span><span>Visitas agendadas</span></div>{Object.keys(grouped).length === 0 ? <div className="empty">No hay visitas para este día.</div> : Object.entries(grouped).map(([hour, items]) => <div className="time-row" key={hour}><div className="time">{hour}<small>{items[0].estado === 'completada' ? 'Finalizada' : 'Programada'}</small></div><div className="cards">{items.map(v => <VisitCard key={v.id} visit={v} onStatus={update} />)}</div></div>)}</section>{modal && <VisitModal clients={clients} operators={operators} onClose={() => setModal(false)} onSaved={() => { setModal(false); load() }} />}</>
}

function VisitCard({ visit, onStatus }) { const status = { agendada: ['Agendada', 'blue'], en_curso: ['En curso', 'orange'], completada: ['Completada', 'green'], cancelada: ['Cancelada', 'gray'], reagendada: ['Reagendada', 'purple'] }[visit.estado]; return <article className="visit-card"><div className="visit-main"><div className="visit-dot" /><div><strong>{visit.cliente.nombre}</strong><p>{visit.cliente.direccion}</p><p className="small">{visit.cliente.telefono_whatsapp}</p></div></div><div className="visit-meta"><span className={`pill ${status[1]}`}>{status[0]}</span><span className="operator">{visit.operador?.nombre || 'Sin asignar'}</span><select value={visit.estado} onChange={e => onStatus(visit.id, e.target.value)} aria-label="Estado de visita"><option value="agendada">Agendada</option><option value="en_curso">En curso</option><option value="completada">Completada</option><option value="cancelada">Cancelada</option><option value="reagendada">Reagendada</option></select></div></article> }

function VisitModal({ clients, operators, onClose, onSaved }) { const [form, setForm] = useState({ cliente_id: clients[0]?.id || '', operador_id: operators[0]?.id || '', fecha_hora: `${today}T10:00` }), [error, setError] = useState(''); async function save(e) { e.preventDefault(); try { await request('/panel/visitas', { method: 'POST', body: JSON.stringify(form) }); onSaved() } catch (err) { setError(err.message) } } return <div className="overlay"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">AGENDA</p><h2>Nueva visita</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Cliente<select required value={form.cliente_id} onChange={e => setForm({ ...form, cliente_id: e.target.value })}>{clients.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label>Operador<select value={form.operador_id} onChange={e => setForm({ ...form, operador_id: e.target.value })}><option value="">Sin asignar</option>{operators.map(o => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></label><label>Fecha y hora<input required type="datetime-local" value={form.fecha_hora} onChange={e => setForm({ ...form, fecha_hora: e.target.value })} /></label><label>Notas<textarea rows="3" value={form.notas || ''} onChange={e => setForm({ ...form, notas: e.target.value })} /></label>{error && <div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Agendar visita</button></div></form></div> }

function Clientes() { const [clients, setClients] = useState([]), [query, setQuery] = useState(''), [modal, setModal] = useState(false), [editing, setEditing] = useState(null); const load = () => request('/clientes').then(setClients); useEffect(() => { load() }, []); const filtered = clients.filter(c => `${c.nombre} ${c.direccion} ${c.telefono_whatsapp}`.toLowerCase().includes(query.toLowerCase())); return <><header className="topbar"><div><p className="eyebrow">GESTIÓN DE CLIENTES</p><h1>Clientes</h1><p className="muted">Administra la información de contacto y ubicación de tus clientes.</p></div><button className="primary" onClick={() => { setEditing(null); setModal(true) }}>＋ Nuevo cliente</button></header><div className="list-toolbar"><input className="search" placeholder="Buscar por nombre, dirección o teléfono" value={query} onChange={e => setQuery(e.target.value)} /></div><section className="client-table"><div className="table-head"><span>Cliente</span><span>Contacto</span><span>Ubicación</span><span>Acciones</span></div>{filtered.map(c => <div className="client-row" key={c.id}><div><strong>{c.nombre}</strong><small>{c.direccion}</small></div><span>{c.telefono_whatsapp}</span><span>{c.lat.toFixed(4)}, {c.lng.toFixed(4)}</span><div><button className="link-button" onClick={() => { setEditing(c); setModal(true) }}>Editar</button></div></div>)}{!filtered.length && <div className="empty">No hay clientes que coincidan con la búsqueda.</div>}</section>{modal && <ClientModal client={editing} onClose={() => setModal(false)} onSaved={() => { setModal(false); load() }} />}</> }

function ClientModal({ client, onClose, onSaved }) { const [form, setForm] = useState(client || { nombre: '', telefono_whatsapp: '', direccion: '', lat: -33.4869, lng: -70.5989 }), [error, setError] = useState(''); async function save(e) { e.preventDefault(); try { await request(client ? `/clientes/${client.id}` : '/clientes', { method: client ? 'PATCH' : 'POST', body: JSON.stringify(form) }); onSaved() } catch (err) { setError(err.message) } } return <div className="overlay"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">CLIENTES</p><h2>{client ? 'Editar cliente' : 'Nuevo cliente'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Nombre<input required value={form.nombre} onChange={e => setForm({ ...form, nombre: e.target.value })} /></label><label>Teléfono WhatsApp<input required value={form.telefono_whatsapp} onChange={e => setForm({ ...form, telefono_whatsapp: e.target.value })} /></label><label>Dirección<input required value={form.direccion} onChange={e => setForm({ ...form, direccion: e.target.value })} /></label><div className="two-col"><label>Latitud<input required type="number" step="any" value={form.lat} onChange={e => setForm({ ...form, lat: Number(e.target.value) })} /></label><label>Longitud<input required type="number" step="any" value={form.lng} onChange={e => setForm({ ...form, lng: Number(e.target.value) })} /></label></div>{error && <div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary">Guardar cliente</button></div></form></div> }

createRoot(document.getElementById('root')).render(<App />)
